# Site settings

title: Tien's note
email: tiendu107@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog serves as my personal journal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tiendu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: tiendu107
linkedin_username: tienhdu
github_username:  tiendu

# Configure the plugin here
paginate_path: "/blog/page:num/"
paginate: 3

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-category-pages
permalink: /:year/:month/:day/:title:output_ext
