# Site settings

title: Tien's notes
email: tiendu107@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tiendu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: tiendu107
linkedin_username: tienhdu
github_username: tiendu

# Configure the plugin here
paginate_path: "/page:num/"
paginate: 5

# Build settings
theme: minima
# remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-category-pages
#   - jekyll-remote-theme
permalink: /:year/:month/:day/:title:output_ext
